language: julia
os:
  - linux
julia:
  - 0.4
  - nightly
notifications:
  email: false
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgdal1h
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("RasterIO"); Pkg.test("RasterIO"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("RasterIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
